# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jenny Veens
email: jennyveens@gmail.com
description: Jenny Veens is a Web Developer in Toronto, ON. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jennyveens.com" # the base hostname & protocol for your site
# url: "http://localhost:4000"
twitter_username: jennyveens
github_username:  jveens
codepen_username: jennyveens
linkedin_url: https://ca.linkedin.com/in/jennyveens
email_address: jennyveens@gmail.com

# Build settings
markdown: kramdown
